### ISSUE TITLE
Add appropriate licenses

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#101]
The whole  repository needs appropriate license files. I will have a test release to our own servers without but they should be added ASAP. @lucasb-eyer I know you are not involved with the people tracker but you are the only one caring at least a bit about it. I will assign this to you and it would be great if you could add the appropriate licenses to the packages from Aachen.

**Comment by lucasb-eyer** [comment]
Just letting you know it's high prio on my TODO list. Will get to it soon.

**Comment by cdondrup** [comment]
Thank you. Much appreciated.
