### ISSUE TITLE
Installing through apt-get

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_perception_people#103]
Not sure if this is the right place to report. Today I wanted to set-up a VM for strands dev on my laptop and I ran into this:

```
beyer@grimbergen:~$ apt-get update
beyer@grimbergen:~$ apt-cache search strands
```

> ros-hydro-strands-morse - The strands_morse package
> ros-hydro-strands-perception-people - The strands_perception_people metapackage
> ros-hydro-strands-webtools - Remote control our robots via a browser

```
beyer@grimbergen:~$ sudo apt-get install ros-hydro-strands-perception-people
```

> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> ros-hydro-strands-perception-people : Depends: ros-hydro-bayes-people-tracker-logging but it is not installable
>                                        Depends: ros-hydro-perception-people-launch but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

```
beyer@grimbergen:~$ apt-cache search ros-hydro-bayes-people-tracker-logging
```

> (nothing)

```
beyer@grimbergen:~$
```

I followed ROS' ubuntu installation tutorial and then our [wiki tutorial](https://github.com/strands-project-releases/strands-releases/wiki). Am I missing something, or is the repo missing something?

ping @marc-hanheide

**Comment by marc-hanheide** [comment]
the problem is that all this is just being build in this very minute. See http://lcas.lincoln.ac.uk/jenkins/view/Releases/ now and you'll see the build is scheduled. Bear with us ;-)

**Comment by lucasb-eyer** [comment]
I see, sorry for the noise.
