### ISSUE TITLE
/mdl_people_tracker/image and /upper_body_detector/image do not publish anything

### ISSUE THREAD

**Issue by ferdianjovan** [strands-project/strands_perception_people#107]
Hi all,

I just updated the strands_perception_people in Bob and something I notice is that those two topics do not publish any information. Everything else is working fine.

Any idea what I should check?

Thanks.

**Comment by cdondrup** [comment]
I have just tested it in simulation but it seems to work fine for me... You do have a camera image for the normal topics `/head_xtion/rgb/image_color` and `/head_xtion/depth/image`? It might be that just the leg_detector gives you results but the cameras are not working. You can also try to turn on the `/upper_body_detector/marker_array` MarkerArray visualisation to check if the upper body detector is really running.
Otherwise I have no idea...

**Comment by ferdianjovan** [comment]
I just checked that the upper_body_detector is not really running. Topics from the upper body detector are there but they do not publish anything.

Any guess?

Thanks.

**Comment by cdondrup** [comment]
The only reason for that could be that one of the supplying modules is not running.
Please check that the following topics publish things:

```
/head_xtion/depth/image_rect_meters
/head_xtion/rgb/image_rect_color
/head_xtion/depth/camera_info
/ground_plane
```

Another reason could be if the PC clocks are not properly synchronised. Are you using `chrony` to sync the PC clocks?

**Comment by ferdianjovan** [comment]
I am not sure about chrony, I think we are using chrony. From chronyc tracking this is the result

```
Reference ID    : 127.127.1.1 ()
Stratum         : 10
Ref time (UTC)  : Thu Oct 30 12:11:53 2014
System time     : 0.000000000 seconds fast of NTP time
Frequency       : 0.000 ppm fast
Residual freq   : 0.000 ppm
Skew            : 0.000 ppm
Root delay      : 0.000000 seconds
Root dispersion : 0.000002 seconds
```

Anyway, The /ground_plane does not publish anything.

**Comment by cdondrup** [comment]
If the ground plane is not published then that will be the reason.
Is there anything on `/ptu/state`? What are you launching exactly?

**Comment by ferdianjovan** [comment]
Nothing in /ptu/state. I am launching people_tracker_robot.launch, openni_wrapper launch file and standard bob-bringup.launch from strands_bob.

**Comment by cdondrup** [comment]
Ok, then the ptu is somehow not running... The state is used to transform the ground plane when the PTU is tilted. Please check why that is not the case. Don't really know where this is launched.
Can you move the PTU by publishing to `/ptu/cmd_state` (not sure about the topic name)?

**Comment by ferdianjovan** [comment]
I tried to move the PTU, no luck. Ok then, I will try to open an issue somewhere where this problem belongs.
Thanks.

**Comment by ferdianjovan** [comment]
I had the same problem again but all referred topics are working fine. The result from `chronyc tracking` is 

```
Reference ID    : 147.188.192.104 (ns1.cs.bham.ac.uk)
Stratum         : 5
Ref time (UTC)  : Wed Mar 11 11:53:56 2015
System time     : 0.000002443 seconds slow of NTP time
Last offset     : -0.000052174 seconds
RMS offset      : 0.000388701 seconds
Frequency       : 55.996 ppm fast
Residual freq   : -0.002 ppm
Skew            : 0.158 ppm
Root delay      : 0.009241 seconds
Root dispersion : 0.081092 seconds
Update interval : 256.3 seconds
Leap status     : Normal
```

Any idea about the problem?

**Comment by cdondrup** [comment]
For the upper body detector these topics:

```
Subscriptions: 
 * /ground_plane [ground_plane_estimation/GroundPlane]
 * /head_xtion/rgb/image_rect_color [sensor_msgs/Image]
 * /head_xtion/depth/camera_info [sensor_msgs/CameraInfo]
 * /head_xtion/depth/image_rect_meters [sensor_msgs/Image]
```

Need to publish. If they do, you should have an image. Never mind the mdl tracker since we are not using this any more and it is not part of the default startup any more since the latest update.

For the ground plane its

```
Subscriptions: 
 * /ptu/state [sensor_msgs/JointState]
```

Needs to publish. Can you check all those please?

**Comment by cdondrup** [comment]
Also, did you start in on the machine which has the head_xtion connected? Otherwise data transfer might be too slow:

```
roslaunch perception_people_launch people_tracker_robot.launch machine:=machine_name user:=user_name
```

**Comment by ferdianjovan** [comment]
Yup, they are publishing data. I got image from head_xtion/rgb/image. 

Is this because of synchronization?

**Comment by cdondrup** [comment]
If all of them are publishing, sometimes the depth image doesn't even though you have a colour image, then it must be synchronisation. You can try to increase the queue size for the ubd: `ubd_queue_size:=20` for example. That queues up more images before it starts throwing them away. Never had that problem on Linda though.

**Comment by ferdianjovan** [comment]
I ruin perception people from the same machine which has the head_xtion connected. I have increased `ubd_queue_size:=30`, still no luck. 

I run upperbody package and ground_plane_estimation only and still no luck. 

```
SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.10
 * /upper_body_detector/WORLD_SCALE: 1.0
 * /upper_body_detector/camera_info_depth: /depth/camera_info
 * /upper_body_detector/camera_namespace: /head_xtion
 * /upper_body_detector/dImHeight: 480
 * /upper_body_detector/dImWidth: 640
 * /upper_body_detector/depth_image: /depth/image_rect...
 * /upper_body_detector/distance_range_accepted_detections: 7
 * /upper_body_detector/evaluation_NMS_threshold_LM: 0.25
 * /upper_body_detector/evaluation_greedy_NMS_overlap_threshold: 0.3
 * /upper_body_detector/evaluation_greedy_NMS_threshold: 0.25
 * /upper_body_detector/evaluation_inc_cropped_height: 20
 * /upper_body_detector/evaluation_inc_height_ratio: 0.2
 * /upper_body_detector/evaluation_nr_scales: 1
 * /upper_body_detector/evaluation_scale_stride: 1.03
 * /upper_body_detector/evaluation_stride: 3
 * /upper_body_detector/freespace_maxX: 3
 * /upper_body_detector/freespace_maxZ: 7
 * /upper_body_detector/freespace_max_depth_to_cons: 7
 * /upper_body_detector/freespace_minX: -3
 * /upper_body_detector/freespace_minZ: 0
 * /upper_body_detector/freespace_scaleX: 20
 * /upper_body_detector/freespace_scaleZ: 20
 * /upper_body_detector/freespace_threshold: 500
 * /upper_body_detector/ground_plane: /ground_plane
 * /upper_body_detector/inc_height_ratio: 0.0
 * /upper_body_detector/inc_width_ratio: 0.2
 * /upper_body_detector/max_height: 2.1
 * /upper_body_detector/min_height: 1.0
 * /upper_body_detector/nOffset: 0
 * /upper_body_detector/numberFrames: 1000000
 * /upper_body_detector/queue_size: 5
 * /upper_body_detector/region_size_threshold: 10
 * /upper_body_detector/rgb_image: /rgb/image_rect_c...
 * /upper_body_detector/template_size: 30
 * /upper_body_detector/upper_body_bb_centres: /upper_body_detec...
 * /upper_body_detector/upper_body_detections: /upper_body_detec...
 * /upper_body_detector/upper_body_image: /upper_body_detec...
 * /upper_body_detector/upper_body_markers: /upper_body_detec...
 * /upper_body_detector/upper_body_template: [0, 0, 0, 0, 0, 0...
 * /upper_body_detector/x_size: 150
 * /upper_body_detector/y_size: 150

NODES
  /
    upper_body_detector (upper_body_detector/upper_body_detector)
```

```
SUMMARY
========

PARAMETERS
 * /ground_plane/distance: 1.7
 * /ground_plane/ground_plane: /ground_plane
 * /ground_plane/normal: [0.0, -0.99999, 0...
 * /ground_plane/ptu_state: /ptu/state
 * /rosdistro: indigo
 * /rosversion: 1.11.10

NODES
  /
    ground_plane (ground_plane_estimation/ground_plane_fixed)
```

Any idea?

**Comment by cdondrup** [comment]
can you post the rqt graph?

**Comment by ferdianjovan** [comment]
Sorry for the delay. This is the rqt_graph.

![rosgraph](https://cloud.githubusercontent.com/assets/7427096/6668298/d8ff9cf8-cbe9-11e4-987a-8c446a6623f1.png)

**Comment by cdondrup** [comment]
That actually looks good. If it is not synchronisation and if everything is publishing, it should work. Can't really tell you anything else :(
Maybe you can ask @lucasb-eyer to have a look if he is around ;)

**Comment by ferdianjovan** [comment]
Ah ok, really thanks for your help. It drives me crazy :)

**Comment by lucasb-eyer** [comment]
It indeed is the clock. You can see that by `rostopic echo`ing all topics that the UBD subscribes and look at their timestamp. Today there was a huge discrepancy of about 1.8k seconds between `/head_xtion/depth/camera_info` and `/ground_plane`.

After running `sudo ntpdate betty`, and then restarting all perception-related nodes, everything works fine. The weird thing is that we ran `sudo ntpdate betty` a few days ago already, so something's weird about betty.
