### ISSUE TITLE
Do not set build mode in cmake file but rely on people using the right build mode

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#11]
People are supposed to use the release build type when compiling the stable version using `catkin_make -DCMAKE_BUILD_TYPE=Release`. So we would not need the explicit build type statement in our CMakeLists.txt

**Comment by cdondrup** [comment]
I think we can leave it like it is for the moment since no one ever complained about not being able to build in debug mode.

**Comment by lucasb-eyer** [comment]
:+1:
