### ISSUE TITLE
[bayes_people_tracker_logging] Add logging of current edge and node

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#113]
By request from @Jailander the node also has to log the current edge the robot is traversing and the current node it is at. Since both of them are just published as string it will only create an implicit dependency on  `strands_navigation`. If nothing is published it will still log the people tracks without the edge and node information.

@Jailander, can you please post the topics on which those are published?

**Comment by Jailander** [comment]
The topic name is `/current_edge`, it is a `String` message type with the following format when navigating `'%s_%s--%s' %(Origin, Target, topol map name)` and `none` when no edge is being navigated.

**Comment by cdondrup** [comment]
@jailander is this still necessary? I remember we talked about this and for some reason I didn't do anything afterwards ;) Do we still need this?

**Comment by cdondrup** [comment]
No answer. I'll close this. Please reopen if necessary @Jailander

**Comment by Jailander** [comment]
For sme crazy reason I didn't receive your previous notification yes it would be nice to have it, it's not a big hassle and the benefit is important. 
But on the other hand  correct me if I'm wrong @marc-hanheide I thought logging the current node/edge was going to be standard now, @hawesie mentioned something about adding it on the meta information of every logged msg, so I'm not sure if @cdondrup has to do something or not. 
Christian can you reopen whilst this is cleared? I don't have permissions to do so in this repo
