### ISSUE TITLE
Removing release branches

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#121]
Maintaining the release branches has become a bit of a pain. @lucasb-eyer is it possible to release the devel branches including your code? We could not make it install anything and not add it to the metapackage if you don't want people to use it but I would really like to have a cleaner structure. If that is OK for you I will remove the release branches and release form the devel branches. I can also take care of adjusting the package.xml and CMakelists.txt files for your packages accordingly.

**Comment by lucasb-eyer** [comment]
I'm ok with that and thanks for adjusting the files for me, I wouldn't know how myself!

**Comment by cdondrup** [comment]
Just tested the new indigo packages on the robot. Work fine. I therefore will remove the indigo-release branch. 
The hydro-release branch will stay as it is, not being maintained. If anyone needs the hydro version with the latest changes desperately, please open a new ticket.
