### ISSUE TITLE
Create node to log raw data

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#142]
Necessary for ground-truthing tracker results. See discussion here: #141

**Comment by cdondrup** [comment]
We decided against logging all the raw data for now and just use #154. If @ferdianjovan needs such a component, please re-open.

**Comment by lucasb-eyer** [comment]
If I am included in the "we," I don't remember discussing this explicitly. But we do have enough raw data from last visit at AAF, so I agree that we don't need this (yet).

**Comment by cdondrup** [comment]
Yes, you are. We said so before starting to write the logging nodes ;)

**Comment by ferdianjovan** [comment]
just to clear this up, so no node stores people_tracker message, doesnt it?

**Comment by cdondrup** [comment]
Of course there will be one @ferdianjovan. See #155.
We just won't log raw RGBD or laser data. Please hav a look at the PR and let me know if you want anything else stored.

**Comment by ferdianjovan** [comment]
Ah, ok. Thanks for the info. No, that will be enough for me :)
