### ISSUE TITLE
supporting ROS type `people_msgs/People`

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_perception_people#143]
It would be very beneficial, e.g. to use the [social costmaps](https://github.com/marc-hanheide/navigation_layers/tree/indigo/social_navigation_layers) of [Lu!! et al](http://www.cse.wustl.edu/~dvl1/publications/LayeredCostmaps.pdf) to have our people tracker publishing on the `/people` topic (type: [`people_msgs/People`](http://docs.ros.org/api/people_msgs/html/msg/People.html)):

```
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
people_msgs/Person[] people
  string name
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Point velocity
    float64 x
    float64 y
    float64 z
  float64 reliability
  string[] tagnames
  string[] tags
```

So, my question is: Is this easily possible? It seems to me it should be, any reasons why we haven't used this before? @ferdianjovan @cdondrup? I assign to @cdondrup for now to get an answer. Doesn't mean I expect you to implement this.

**Comment by cdondrup** [comment]
Should be easy enough to do. The only thing I can't really figure out is, what `name`, `tags`, `tagnames`, and `reliability` is used for. A quick grep on the navigation_layers repo told me that all these values are never used.
I'll set `name` to the uuid and will also add a `tag` for it. The position and velocity comes out of the tracker anyway and since my code is always fail safe I will just set the reliability to 1.0 ;)

**Comment by marc-hanheide** [comment]
Great. We can then have the student do some experiment with that proxemics layer.

**Comment by ferdianjovan** [comment]
Ah yes, that one, I came across that a long time ago and I forgot about it. About the velocity, what will you put there? Will it be the velocity between two poses or be the average velocity?

**Comment by cdondrup** [comment]
It will be the velocity used by the tracker for the prediction. Since it uses a constant velocity model, I assume it'll be the average velocity. I didn't check the actual implementation yet, though.

**Comment by cdondrup** [comment]
Done. Needs testing though.

**Comment by marc-hanheide** [comment]
Thanks!
