### ISSUE TITLE
Add people tracker filter based on map

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#175]
Inspired by the laser filter for the leg detector, this filter will either take the current map published on `/map` and exclude all detections that are not in free space, i.e. obstacles or unknown, or uses a custom map to do so. Similar to the abandoned `no_go_map` this `no_ppl_map` allows you to draw black areas into the map, where you won't accept any people tracks. This is useful if you have an environment that is prone to false positives in certain areas where equipment is standing around and persons are unlikely to appear. The node just takes all the tracker messages and filters them based on their `x,y` location in a simple map look-up.

This is basically done and this issue only serves as a reminder to myself to clean-up the code and open a PR once the HRI deadline is over.

**Comment by lucasb-eyer** [comment]
neat, will use when it's in.
