### ISSUE TITLE
Change number of frames for visual confirmation

### ISSUE THREAD

**Issue by lcluz** [strands-project/strands_perception_people#207]
Hi. I'm trying to put to work the tracker with external cameras, a onboard Asus and a laser. With the Asus I'm using my own rgb detector and then using depth to map to base_link, and publishing has a PoseArray. I've been tuning the parameters (velocity and measurement noises) and tried different fps for the tracker, and could never have a new tracker instance.
I'm thinking that maybe the number of frames for visual confirmation might be very high, and with my low fps detection it might take a long time time to get a new track.
Could you tell me how many frames do you consider and how to change it?
Thanks

**Comment by cdondrup** [comment]
Hi, by default it needs 5 detections in 0.2 seconds which is defined [here](https://github.com/LCAS/bayestracking/blob/dba55e38d59159d6d7a9ef70dd17909e4bdc3084/include/bayes_tracking/multitracker.h#L81). This multitracker is used [here](https://github.com/strands-project/strands_perception_people/blob/indigo-devel/bayes_people_tracker/include/bayes_people_tracker/simple_tracking.h#L174). You could try increasing the time or lowering the number of detections.

There was a pull request by @scosar where he tried to expose this a little better. But it didn't build anymore so we had to revert it. I'll ping him again. For now you can try to either change the default values in the [bayestracking library](https://github.com/LCAS/bayestracking) or insatiate the MultiTracker with different parameters.

**Comment by lcluz** [comment]
I changed the default values and it worked. Thank you very much

**Comment by cdondrup** [comment]
No problem. I'll close this issue then. If you run into any other problems, just open a new one ;)
