### ISSUE TITLE
upper_body_detector does not subscribe to anything

### ISSUE THREAD

**Issue by Dagu12s** [strands-project/strands_perception_people#234]
Im using the upper_body_detector in a simulated enviroment with a simulated intel realsense d435. The problem is that the upper_body_detector does not subscribe to anything.
Im using the upper_body_detector.launch and the really fixed ground plane. 
Any idea?

Thank you very much

**Comment by cdondrup** [comment]
Hi, to save resources the upper body detector only subscribes to the image topics if another node subscribes to any of the topics advertised by the detector. See https://github.com/strands-project/strands_perception_people/blob/kinetic-devel/upper_body_detector/src/main.cpp#L439-L462

**Comment by Dagu12s** [comment]
Hi, Thank you very much for the response. I corrected that but it is not doing any detection. I will try to use a different camera configuration but i dont know what else to try. Any idea?
