### ISSUE TITLE
Outsource ground plane estimation?

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#29]
I am not particularly happy that the ground plane is produced as a byproduct of the upper body detector. This does not seem very intuitive to understand. I would like to move the estimation to a separate node but I don't know if that creates too much extra computation time. What's your opinion on that @dennismitzel ?

**Comment by hawesie** [comment]
@kunzel has done some plane estimation work recently and may be able to provide some input.

**Comment by nilsbore** [comment]
Same goes for @jekekrantz.

**Comment by dennismitzel** [comment]
I can change it and create a separated module only for GP estimation.

**Comment by johnfolk** [comment]
So Johan has quite a lot of plane extraction tools and can put some code here but we are unsure what you want exactly.  Is the input one frame and the output the normal and a point on the plane or the pixels with the plane or something else?  Also is this assuming only the image or the whole tf can be used?

**Comment by cdondrup** [comment]
I don't know what we are using at the moment to estimate the ground plane (maybe @dennismitzel can answer that) but since it is supposed to run on the robot it would be good if the whole tf is used.

**Comment by jekekrantz** [comment]
So if we have the TF it is not really the equation of the plane that is desired but rather the pixels in the image that is to be considered part of the ground plane that is interesting? Is it meant to be used to find the area where the robot could go?

**Comment by dennismitzel** [comment]
the output of the ground plane estimator right now is only the normal and a point on the plane and I use only one image. I can output the points on the ground plane as well if it is really required for some components?

**Comment by kunzel** [comment]
Hi, a Master student of us is currently using PCL to segment point cloud data in order to detect table tops etc (http://pointclouds.org/documentation/tutorials/planar_segmentation.php). I was using information about normals to classify voxels in an octomap as supporting surface. 

I think in general it would definitely make sense to have a common tool box for the extraction of planes as it seems a very essential task for many problems and groups.  Of course, we are happy to contribute our code as well. Although I believe that the developments of @jekekrantz and @dennismitzel are more sophisticated and thereby more suitable as a starting point for such a tool box.  

In particular, I would be interested in a supporting plane extraction whereby the full TF can be used. Does anyone of you have some code for this? If so, what is the output? Classified points? Bounding box of the plane?

**Comment by johnfolk** [comment]
I think this is sensible.  Right now Johan has algorithms implemented that find and refine planes without reference to the TF but that can easily be included to for example identify (only) the ground plan.  Our output is a segmentation of the larger planes, along with the parameters of the plane.  Our goal, (and we are pretty much there) is to separate for example notebooks from the desktop they are laying on.  

So to get just the ground plane we might be too fussy and too complex but it will sure work.

I think a toolbox with various plane extractors makes sense for now and then we can see how to use them later.

**Comment by johnfolk** [comment]
Sorry did not mean to close

**Comment by cdondrup** [comment]
As you can see the ground plane estimation is now a separate package. I don't know if the functionality is comparable to the stuff @jekekrantz did but this is the one which is currently used for the people detection. Maybe @dennismitzel can give a short overview of what it does and how it works.
It might also be a good idea to move this package into a general perception repository in the long run.

**Comment by mzillich** [comment]
Hi,

of course we also have plane extraction code. All based on PCL. So I 
guess by and large it does not make too much difference.

M

On 08/15/2013 11:14 PM, Lars Kunze wrote:

> Hi, a Master student of us is currently using PCL to segment point cloud
> data in order to detect table tops etc
> (http://pointclouds.org/documentation/tutorials/planar_segmentation.php). I
> was using information about normals to classify voxels in an octomap as
> supporting surface.
> 
> I think in general it would definitely make sense to have a common tool
> box for the extraction of planes as it seems a very essential task for
> many problems and groups. Of course, we are happy to contribute our code
> as well. Although I believe that the developments of @jekekrantz
> https://github.com/jekekrantz and @dennismitzel
> https://github.com/dennismitzel are more sophisticated and thereby
> more suitable as a starting point for such a tool box.
> 
> In particular, I would be interested in a supporting plane extraction
> whereby the full TF can be used. Does anyone of you have some code for
> this? If so, what is the output? Classified points? Bounding box of the
> plane?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project/strands_perception_people/issues/29#issuecomment-22731196.

## 

Dr. Michael Zillich
ACIN Institute of Automation and Control
Vienna University of Technology
(DVR-Number 0005886)
Gusshausstr 27-29/E376, 1040 Vienna, Austria
zillich@acin.tuwien.ac.at   http://users.acin.tuwien.ac.at/mzillich
Tel: +43 1 58801 376648     Fax: +43 1 58801 37698

**Comment by cdondrup** [comment]
No comments since over a year ago. The current ground plane estimation seems to work fine for the detector. If there is a  unified way of getting the plane at some point we could reopen this.
