### ISSUE TITLE
Jenkins reported broken build

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_perception_people#51]
There seems to be a dependency problem once again, now that OpenNI is compiled by "us". It seems to only show up in the massively parallel build of jenkins. 
As fas as I understand this, we'd now have to include our OpenNI (in https://github.com/strands-project/scitos_robot/tree/master/openni_wrapper) as a build dependency in all modules that use it. So I think also @RaresAmbrus, @nilsbore, @gestom, @AlexanderHermans, and @hawesie might find this useful. Is my assumption that we need to include the openni_wrapper as a dependency correct?

```
[ 83%] Building CXX object strands_perception_people/strands_upper_body_detector/CMakeFiles/upper_body_detector.dir/src/Math.cpp.o
./../../../../Bin/Intermediate/x64-Release/PS1080Console/PS1080Console.o: file not recognized: File truncated
collect2: ld returned 1 exit status
make[4]: *** [../../../../Bin/x64-Release/PS1080Console] Error 1
make[3]: *** [Source/Drivers/PS1080/PS1080Console] Error 2
make[3]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object strands_perception_people/strands_visual_odometry/CMakeFiles/visual_odometry.dir/3rd_party/fovis/libfovis/initial_homography_estimation.cpp.o
Linking CXX executable /var/lib/jenkins/jobs/catkin_make_strands_desktop_full/workspace/catkin_ws/devel/lib/strandsbag/image_player_node
[ 83%] Built target image_player_node
[ 83%] Building CXX object strands_perception_people/strands_pedestrian_tracking/CMakeFiles/pedestrian_tracking.dir/src/Kalman.cpp.o
Scanning dependencies of target costmap_2d_generate_messages
[ 83%] Built target costmap_2d_generate_messages
[ 83%] Building CXX object strands_perception_people/strands_upper_body_detector/CMakeFiles/upper_body_detector.dir/src/pointcloud.cpp.o
[ 83%] Building CXX object strands_perception_people/strands_upper_body_detector/CMakeFiles/upper_body_detector.dir/src/ROI.cpp.o
make[2]: *** [/var/lib/jenkins/jobs/catkin_make_strands_desktop_full/workspace/catkin_ws/devel/lib/openni_wrapper/openni_wrapper] Error 2
make[1]: *** [scitos_robot/openni_wrapper/CMakeFiles/openni_wrapper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Finished: FAILURE
```

**Comment by RaresAmbrus** [comment]
Strange. The package is openni_wrapper, and the Openni sources are compiled from its CMakeLists file via a Cmake custom command. But on my machine the rest of the repository compiles without adding this dependency to other packages. 
(BTW I think the PS1080Console error is from something else).

**Comment by marc-hanheide** [comment]
But, catkin runs all compilations in parallel. It seems to me that something from strands_perception_people tried to compile with a half-finished openni setup, doesn't it? `PS1080Console` is from OpenNI isn't it?

**Comment by RaresAmbrus** [comment]
Ah yes yes, you're right, PS1080Console is a file from OpenNI. I'll try to replicate this on my machine and see if I can come up with a solution, but I guess adding openni_wrapper as a dependency could be a way to go.

**Comment by cdondrup** [comment]
Not related to the strands_perception_people. The openni_wrapper fails to build and the output is just mixed up with the strands_perception_people output.

**Comment by marc-hanheide** [comment]
weird, that is... I trigger the build again now to see what the problem is

**Comment by RaresAmbrus** [comment]
In the meantime I've found an issue in the openni_wrapper - it builds two targets, an executable and a library, both of which depend on the compilation of the 3rd party openni sources; I am modifying the CMake file a bit to make sure that both the targets don't try to compile the 3rd party sources at the same time. I'll merge in a bit.

**Comment by RaresAmbrus** [comment]
I've added a small fix in scitos_robot, @marc-hanheide  can you please check out the latest version and try again? Let's see if there are any other errors.

**Comment by marc-hanheide** [comment]
jenkins just reported `SUCCESS`, so, we considered this fixed by https://github.com/strands-project/scitos_robot/pull/28

**Comment by RaresAmbrus** [comment]
Great!
