### ISSUE TITLE
pedestrian localisation should unsubscribe from the people detection topics

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#52]
- [x] if no one subscribes to the localisation, unsubscribe from ppl detection topics to reduce computational load.
- [x] check nodes for same issue

**Comment by cdondrup** [comment]
I am currently trying to solve this and I am now looking for the best way to do it. Maybe one of you knows a good way to implement such behaviour.
Problem: The pedestrian tracker is very modular now which means that we have 2-3 basic components which work on camera and tf data, 1 intermediate component using camera data and the data from the basic components, another intermediate layer which relies on all of the underlying nodes, and a high level layer which converts everything into useful ros data. Each of these components uses a reasonable amount of processing power. To prevent unnecessary processing if no one is subscribed to the high-level component I have to find a way of suspending these nodes and have them idle until someone subscribes.

Possible solution:
The high level node checks for the number of subscribers and if it is 0 it just does no calculations at all.
Problem: It is still subscribed to the underlying nodes which prevents me from doing the same for these ones.
A possible solution for this would be to let the high-level node unsubscribe from every topic and only subscribe again if itself has at least one subscriber. Then I could repeat this for the underlying components. I tested this possibility using `ros::SubscriberStatusCallback` and it works quite well. This callback is triggered every time someone subscribes or unsubscribes to the topic you publish and allows therefore an easy subscribe or unscubscribe on my side. Now I don't really know if that is the way to go because it contacts the roscore quite often to create all the subscriptions or unsubscribe which looks a bit messy and might also fail at some point.

Does anyone know a better way of doing it? I had a brief look at nodelets for example but it did not look like that does what I want. (Since I have never used nodeletes I might be wrong though.)
Tips and hints very welcome.

**Comment by marc-hanheide** [comment]
I would actually say this sounds exactly how I'd do it... I don't think there's a problem with repeatingly (un) subscribing as long as you don't do it at 100Hz.

**Comment by cdondrup** [comment]
Implemented it the described way. See pull request #55.
Will close. If someone has a better way of doing it, just reopen the topic.
