### ISSUE TITLE
Make the "heads" a action server.

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_perception_people#57]
Using a person-id in a 'start' signal to start computing the head's angle and publish it continuously, until the goal is canceled.

**Comment by cdondrup** [comment]
@lucasb-eyer any news on that? Is that still valid?

**Comment by lucasb-eyer** [comment]
I think it's a service now. I always confuse "service" and "action server." Anyways, we can close this until someone actually needs to use the heads output and has further requirements.
