### ISSUE TITLE
New logging mechanism of people tracks 

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_perception_people#70]
@cdondrup, the new logging mechanism looks really good! Just one question, why did you not use the `TimeSynchronizer` for the `/robot_pose` too? Can this cause a problem when the robot_pose updates are received faster than the synchronized ones? Especially, because the human pose is in /base_link coordinates, right?

btw the projected positions of the people tracker are in the /map frame, right?

**Comment by kunzel** [comment]
One more thought: as the IDs of the tracker are reused after a restart I would be good if we could use another ID which differentiates between different runs of the tracker. This could be either the starting time of the tracker or a md5 hash. This why we could find the track of a person quite easily.  @cdondrup, what do you think?

**Comment by cdondrup** [comment]
I would have loved to use the timesynchroniser but the robot_pose is not stamped.

By default everything is in in base_link but if you run the ppl perception with `tf_target_frame:=/map` it will be transformed to map. See: https://github.com/strands-project/strands_perception_people/tree/hydro-devel/strands_perception_people_launch#pedestrian_tracker_robotlaunch
also, you have to run it with `log:=true` to start logging.

Your idea for the id is nice. I will look into it.

**Comment by kunzel** [comment]
Oh I see, I didn't know that the target_frame can be configured in that way. Reading the documentation would have helped ;) However, in the long run we want to collect the people track data in the global frame whereas you want to have it local, right? What do you think about having both information in the message? So, poses of people in both the global and the local frame. Because running people perception with different target frames at the time would not be a good solution. Or is the global position in map frame already included the `Logging.msg` under  `pedestrian_tracking`? Then we don't need to add it? 

Is the pose of the `people` array really a pose or only a position?

**Comment by cdondrup** [comment]
I don't really mind either of the target frames. We could save both: base_link and what ever was set for the target_frame or I can save the tf from base_link to target_frame... I will think about it. Maybe we could also change the default target frame to /map as I think that will be more useful for other people as well?!

The pose is just a position atm but I made it a pose to have the opportunity of incorporating the orientation as well (which is given by the tracker but not very reliably). But you are right, currently the orientation will always be 0 0 0 1

**Comment by kunzel** [comment]
Cool, if we can assume that the pose is reported in map_frame it would be very helpful. Also if you could find a way to add a unique tracker session ID to the poses it would be really great. Then we could search and identify human tracks quite easily. Please let me know if you need any help for this. 

In the next days and weeks we will create some data structures and methods for representing and analysing human motion patterns. We will keep you posted on this matter. Maybe you this data will be also interesting for you.

**Comment by cdondrup** [comment]
I think this should be solved now.
