### ISSUE TITLE
Tracking ID in Logging.msg

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_perception_people#72]
The tracking ID that is used at the top level in the Logging message should also be used for the pedestrian tracking message stored inside the logging message. Otherwise the data cannot be easily associated if several people are tracked. 

@cdondrup do you have time to look into it? Or should I make the change and make a pull request?

**Comment by cdondrup** [comment]
I can do it tomorrow. Of that's early enough. Shouldn't be much of an effort.

**Comment by kunzel** [comment]
Great, thanks.

**Comment by kunzel** [comment]
Thanks @cdondrup!
