### ISSUE TITLE
Create release branch?

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#83]
Since some of the code in here is still under development, I think it would be nice if we could create a release branch. 
@lucasb-eyer am I right that you don't want your head angle code release already? Otherwise we don't need any specific branch.

**Comment by lucasb-eyer** [comment]
You're right, because it doesn't currently work.

If I had time till after Leeds (I'll be on vacation till then), I could fix it and then I'd have no problem releasing it.

**Comment by cdondrup** [comment]
Ok, so I will create a release branch for the first release.

**Comment by cdondrup** [comment]
Just did.
