### ISSUE TITLE
People perception release and licensing 

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#84]
The last thing I heard is that the code for the people tracker could be released because it is published now. Hence, I would love to make it publicly available to maybe attract others to use it and contribute.

The question is @lucasb-eyer, is Aachen satisfied with using the MIT license for the tracker and detector?

**Comment by lucasb-eyer** [comment]
Since you cut out the GPL-infested dependencies, you can. Though we did [use](http://www.vision.rwth-aachen.de/software/realpdt/realpdt) the BSD-3 license for it, so I'd suggest to use that one here too. If that's a problem and you absolutely want MIT, let me know today and I'll ask Bastian; he'll likely accept.

**Comment by cdondrup** [comment]
Actually, I think the MIT license would give people more freedom to contribute. So if Bastian is ok with that, I would like to use MIT.

**Comment by lucasb-eyer** [comment]
AFAICT the only thing it would allow in addition, is that people contribute pattern-encumbered code, which I don't think we want. Anyways, I'll ask after lunch.

**Comment by marc-hanheide** [comment]
So, can we change this repo to be public now? Just want to check once again @lucasb-eyer

**Comment by cdondrup** [comment]
According to what Lucas wrote: 

"@marc-hanheide we can make the repo public, but the strands_head_orientation and opencv_warco shouldn't go to the "public ros" (or whatever the name) build-track yet!
though that node will most likely crash right now. Working on fixes this week." 

we could make it public. The head orientation and opencv warco will not be made available as a package because I'm going to create a release branch that only contains the subset of packages necessary to run the ppl perception the way we do on our robots.

**Comment by marc-hanheide** [comment]
Here is what github says when I'm trying to make it public:

"Current forks will remain private and will be separated from this repository". 

![screen shot 2014-10-16 at 19 34 29](https://cloud.githubusercontent.com/assets/1153084/4668167/22f0c04c-5563-11e4-85e1-d7aa7f1ae550.png)

https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#changing-a-private-repository-to-a-public-repository states that current forks will remain private, but one would have to pay for it or access will be barred. Or they can be made public individually. Looking at it there are 8 forks:
![screen shot 2014-10-16 at 19 40 24](https://cloud.githubusercontent.com/assets/1153084/4668280/f8133ca0-5563-11e4-8ffc-fd58a903b2d8.png)

so, @cdondrup @dennismitzel @ferdianjovan @gestom @hawesie @kunzel @lucasb-eyer @OMARI1988, be prepared!

**Comment by cdondrup** [comment]
After all PRs are merged I think we can assume that shouldn't be a problem. But the people you listed should be aware of that, that's true.

**Comment by lucasb-eyer** [comment]
argh, my fail, in gitter.im I said I'd check back at the beginning of the week but then got caught up with other stuff. Sorry for the radio silence. I'm ok with @cdondrup 's suggestion.

Edit: is there still something that I need to clarify?

**Comment by marc-hanheide** [comment]
nope... if you say it's ok, I'm going to press the button and make it public.

**Comment by hawesie** [comment]
Press!

**Comment by marc-hanheide** [comment]
done!
