### ISSUE TITLE
Create compliant package.xml files

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#86]
I would of course volunteer as a maintainer for all the packages and author for those I wrote. Regarding the people tracker and upper body detector, does @dennismitzel still want to be involved and are there other authors that have to be mentioned? @lucasb-eyer, it would be nice if you could find that out.
Also #84 needs to be answered first.

**Comment by lucasb-eyer** [comment]
About the authors, only Dennis can tell, but if he doesn't react, I'd wager to say no additional authors.

**Comment by cdondrup** [comment]
Closed via https://github.com/strands-project/strands_perception_people/pull/97
