### ISSUE TITLE
Running standalone?

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_perception_people#89]
I'm trying to run the people tracker standalone (a PrimeSense stuck on a box). I am launching the following files:

```
roslaunch openni_wrapper main.launch camera:=head_xtion publish_tf:=true
roslaunch strands_perception_people_launch pedestrian_tracker_standalone.launch camera:=head_xtion
```

But when I subscribe to the output topics (pose array, image etc.) I don't see any output. There is also nothing printed in the terminal once the tracker nodes are created. Is this launch file up to date with the new changes?

**Comment by cdondrup** [comment]
Try `roslaunch strands_perception_people_launch pedestrian_tracker_standalone.launch camera_namespace:=/head_xtion` works for me.

Should I change the parameter to `camera` is that more common in the project as a parameter for the namespace?

**Comment by hawesie** [comment]
Sorry mate, I should have read the doc more carefully rather than copying from the `openni_wrapper` call. I think camera is fairly common, but probably not common enough to use generally.

**Comment by cdondrup** [comment]
No problem. Just let me know if you run into more problems.

**Comment by hawesie** [comment]
That worked, thanks. 

Now I see output on `/pedestrian_tracking/pedestrian_array` but the messages on `/pedestrian_tracking/pose_array` all come up empty. It seems related to this error message in the tracker terminal:

```
Warning: Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty
         at line 122 in /tmp/buildd/ros-hydro-tf2-0.4.11-0precise-20140617-0510/src/buffer_core.cpp
```

It looks like it's failing to transform the pedestrians into an empty output tf2 frame. I think there's a parameter I can set for this, so I will try that now

**Comment by hawesie** [comment]
Yep, that fixed it. Maybe by default the pose transform should be done in the frame of tracker? Without this no poses will be generated (and they're easier to work with IMO). My final working commands:

```
roslaunch openni_wrapper main.launch camera:=head_xtion publish_tf:=true

roslaunch strands_perception_people_launch pedestrian_tracker_standalone.launch camera_namespace:=/head_xtion tf_target_frame:=/head_xtion_depth_optical_frame
```

Thanks for your help @cdondrup
