### ISSUE TITLE
Rename package to get rid of 'strands' prefix

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#94]
Since this might be interesting to the whole community (at least I hope so) the packages should be renamed to get rid of the `strands` prefix. Also, the packages have to have names that express what they do, shouldn't be too long, and have to be unique. Especially https://github.com/wg-perception/people claimed a lot of nice names already. Some of the package names work fine with just removing the prefix but especially the pedestrian_tracker needs a more descriptive one.

Suggestions welcome.

**Comment by hawesie** [comment]
We should note these rules for future new packages too!

**Comment by cdondrup** [comment]
Closed via #96 and #98 
Might require further renaming if the ROS people are not convinced by ours.
